# Install dependencies
npm install

# Compile TypeScript
npm run build

# Create .env file
cat <<EOL >> .env
LOG_LEVEL=$LOG_LEVEL
DB_PRODUCT=$DB_PRODUCT
DB_DISCOUNT=$DB_DISCOUNT
SUPERMARKET_WEB_CONFIG_SCHEMA=$SUPERMARKET_WEB_CONFIG_SCHEMA
NOTION_SECRET=$NOTION_SECRET
NOTION_DATABASE_ID=$NOTION_DATABASE_ID
EOL